import Head from "next/head";
import Image from "next/image";
import { FiAlertTriangle } from "react-icons/fi";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>MyShoppe-Zakir's Online Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="text-5xl text-blue-800 text-center my-9 bg-sky-500 border-slate-900 flex justify-center borde uppercase">
        {/* <Image src="/mf2.gif" className='border-slate-900 border-4 mx-auto' height={500} width={1000}></Image> */}
      </div>
      <FiAlertTriangle /> 
    </div>
  );
}
